name: "Orb"
description: "Orb Service addon for Home Assistant"
version: "0.1.2"
slug: "orb"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
ports:
  7443/tcp: 7443
map:
  - config:rw
