name: "Orb"
description: "Orb sensor to continuously monitor network responsiveness and reliability."
version: "0.12.29"
slug: "orb_homeassistant"
init: false
host_network: true
image: "orbforge/orb"
map:
  - share:rw
volumes:
  - /data:/root/.config/orb:rw
arch:
  - aarch64
  - amd64
  - armv7
boot: auto
options: {}
schema: {}
