name: "Orb"
description: "Orb sensor to continuoiusly monitor network responsiveness and reliability."
version: "0.12.24"
slug: "orb_homeassistant"
init: false
host_network: true
image: "5lxnphjgj0.execute-api.us-west-2.amazonaws.com/orb-sensor-6b5bcc"
map:
  - share:rw
volumes:
  - /data:/root/.config/orb:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
boot: auto
options: {}
schema: {}
